/**
 * 회원 더미 데이터
 */

import type { Member } from '@baepdoongi/shared';

export const members: Member[] = [
  // 이름 형식 준수 회원들
  {
    slackId: 'U001',
    displayName: '홍길동/컴퓨터공학과/24',
    realName: '홍길동',
    email: 'hong@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hong',
    isNameValid: true,
    warningCount: 0,
    joinedAt: '2026-01-15T10:00:00Z',
    role: 'admin',
  },
  {
    slackId: 'U002',
    displayName: '김철수/정보통신공학과/23',
    realName: '김철수',
    email: 'kim@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kim',
    isNameValid: true,
    warningCount: 0,
    joinedAt: '2026-01-10T14:30:00Z',
    role: 'staff',
  },
  {
    slackId: 'U003',
    displayName: '이영희/전자공학과/25',
    realName: '이영희',
    email: 'lee@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lee',
    isNameValid: true,
    warningCount: 0,
    joinedAt: '2026-01-20T09:00:00Z',
    role: 'member',
  },
  {
    slackId: 'U004',
    displayName: '박지민/소프트웨어학과/24',
    realName: '박지민',
    email: 'park@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=park',
    isNameValid: true,
    warningCount: 0,
    joinedAt: '2026-01-18T11:20:00Z',
    role: 'member',
  },
  {
    slackId: 'U005',
    displayName: '정수현/컴퓨터공학과/23',
    realName: '정수현',
    email: 'jung@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jung',
    isNameValid: true,
    warningCount: 0,
    joinedAt: '2026-01-05T16:45:00Z',
    role: 'member',
  },
  {
    slackId: 'U006',
    displayName: '최민준/데이터사이언스학과/25',
    realName: '최민준',
    email: 'choi@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=choi',
    isNameValid: true,
    warningCount: 0,
    joinedAt: '2026-01-22T13:00:00Z',
    role: 'member',
  },
  {
    slackId: 'U007',
    displayName: '강서연/정보통신공학과/24',
    realName: '강서연',
    email: 'kang@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kang',
    isNameValid: true,
    warningCount: 1,
    lastWarningAt: '2026-01-10T09:00:00Z',
    joinedAt: '2026-01-08T10:30:00Z',
    role: 'member',
  },
  {
    slackId: 'U008',
    displayName: '윤하늘/컴퓨터공학과/22',
    realName: '윤하늘',
    email: 'yoon@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=yoon',
    isNameValid: true,
    warningCount: 0,
    joinedAt: '2025-03-15T14:00:00Z',
    role: 'member',
  },
  // 이름 형식 미준수 회원들
  {
    slackId: 'U009',
    displayName: '조예진',
    realName: '조예진',
    email: 'jo@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jo',
    isNameValid: false,
    warningCount: 2,
    lastWarningAt: '2026-01-25T09:00:00Z',
    joinedAt: '2026-01-12T11:00:00Z',
    role: 'member',
  },
  {
    slackId: 'U010',
    displayName: 'David Kim',
    realName: '김대현',
    email: 'david@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    isNameValid: false,
    warningCount: 1,
    lastWarningAt: '2026-01-20T10:00:00Z',
    joinedAt: '2026-01-16T15:30:00Z',
    role: 'member',
  },
  {
    slackId: 'U011',
    displayName: '신입생_24',
    realName: '신민수',
    email: 'shin@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=shin',
    isNameValid: false,
    warningCount: 0,
    joinedAt: '2026-01-27T10:00:00Z',
    role: 'member',
  },
  {
    slackId: 'U012',
    displayName: '임준혁/전자공학과/24',
    realName: '임준혁',
    email: 'lim@example.com',
    imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lim',
    isNameValid: true,
    warningCount: 0,
    joinedAt: '2026-01-25T09:30:00Z',
    role: 'member',
  },
];
